import { test, expect } from '@playwright/test';

import { fillAndSubmitForm } from '../helpers/utilities';

test('test', async ({ page }) => {
    await page.goto('https://www.imbankgroup.com/ke/');
    await page.hover('#menu-item-12100');
    await expect(page.locator('#menu-item-12100').getByRole('link', { name: 'About Us' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Who We Are' })).toBeVisible();
    await expect(page.locator('#menu-item-16607').getByRole('link', { name: 'I&M Foundation' })).toBeVisible();
    await expect(page.locator('#menu-item-16608').getByRole('link', { name: 'Annual Reports' })).toBeVisible();
    await expect(page.locator('#menu-item-16608').getByRole('link', { name: 'Annual Reports' })).toBeVisible();
    await expect(page.locator('#menu-item-16609').getByRole('link', { name: 'Directors' })).toBeVisible();
    await expect(page.locator('#menu-item-16610').getByRole('link', { name: 'News' })).toBeVisible();
    await expect(page.locator('#menu-item-16610').getByRole('link', { name: 'News' })).toBeVisible();
    await expect(page.locator('#menu-item-16611').getByRole('link', { name: 'I&M Voices' })).toBeVisible();
    await expect(page.locator('#menu-item-16611').getByRole('link', { name: 'I&M Voices' })).toBeVisible();
    await expect(page.locator('#menu-item-16607').getByRole('link', { name: 'I&M Foundation' })).toBeVisible();
    //await page.getByRole('link', { name: 'Career', exact: true }).click();
    // const pagePromise = page.waitForEvent('popup');
    //await page.getByRole('link', { name: 'Career', exact: true }).click();
    //const page = await pagePromise;
    await expect(page.getByRole('link', { name: 'Career', exact: true })).toBeVisible();
    await expect(page.locator('#menu-item-16613').getByRole('link', { name: 'Partners' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Contact', exact: true })).toBeVisible();
    await expect(page.locator('#menu-item-23229').getByRole('link', { name: 'Corporate Profile' })).toBeVisible();
    await page.getByRole('link', { name: 'Who We Are' }).click();
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - Who We Are' })).toBeVisible();
    await expect(page.getByText('About usWho We Are I&M')).toBeVisible();
    await expect(page.getByText('About us', { exact: true })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('About us');
    await expect(page.locator('#menu-item-12178')).toContainText('Who We Are');
    await expect(page.locator('#menu-item-14104')).toContainText('I&M Foundation');
    await expect(page.locator('#menu-item-11764')).toContainText('Annual Reports');
    //await page.locator('#menu-item-11766').getByRole('link', { name: 'Directors' }).click();
    await expect(page.locator('#menu-item-11766')).toContainText('Directors');
    await expect(page.locator('#menu-item-11770')).toContainText('News');
    await expect(page.locator('#menu-item-11769')).toContainText('I&M Voices');
    await expect(page.locator('#menu-item-11771')).toContainText('Careers');
    //await page.getByRole('link', { name: 'GMT' }).click();
    await expect(page.locator('#menu-item-18017')).toContainText('GMT');
    await expect(page.locator('#menu-item-11773')).toContainText('Partners');
    await expect(page.locator('#menu-item-11765')).toContainText('Contact');
    await expect(page.locator('#menu-item-11765')).toContainText('Contact');
});

test('test who-we-are', async ({ page }) => {
    await page.goto('https://www.imbankgroup.com/ke/about-us/who-we-are/')
    await expect(page.getByRole('heading', { name: 'Strategic Aspiration' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Eastern Africa’s Leading Financial Partner for Growth');
    await expect(page.getByRole('heading', { name: 'Mission (M) and Core Values (' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Mission (M) and Core Values (CV)');
    await expect(page.locator('#page-wrap-in')).toContainText('To be partners of growth for all our stakeholders. We will achieve this through:');
    await expect(page.locator('.feature-17-body-col > .card > .card-body').first()).toBeVisible();
    await expect(page.locator('div:nth-child(2) > .card > .card-body').first()).toBeVisible();
    await expect(page.locator('div:nth-child(3) > .card > .card-body').first()).toBeVisible();
    await expect(page.locator('div:nth-child(4) > .card > .card-body')).toBeVisible();
    await expect(page.locator('div:nth-child(5) > .card > .card-body')).toBeVisible();
    await expect(page.locator('div:nth-child(6) > .card > .card-body')).toBeVisible();
    await expect(page.locator('.non-full-bg')).toBeVisible();
    await expect(page.getByRole('img', { name: 'Our Vision' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Our Vision');
    await expect(page.locator('#page-wrap-in')).toContainText('To become a company where the best people want to work. The first choice is where customers want to do business, and where shareholders are happy with their investment.');
    await expect(page.getByRole('heading', { name: 'Our Culture' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Our Culture');
    await expect(page.locator('#page-wrap-in')).toContainText('"Nurture a culture of fairness to our partners" - This is with regard to three key relationships.');
    await expect(page.getByRole('img', { name: 'About I&M Bank' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('About I&M Bank');
    await expect(page.locator('#page-wrap-in')).toContainText('About I&M BankI&M Bank was founded in 1974 as a financial services company and later converted to a commercial bank.I&M Bank is a wholly-owned subsidiary of I&M Group PLC (previously known as I&M Holdings PLC), a public company, listed at the Nairobi Securities Exchange (NSE). The bank possesses a rich heritage in banking. Having started in 1974, it evolved from a community financial institution to a publicly listed major regional commercial bank offering a full range of corporate and retail banking services.From June 2013, I&M Bank shares are publicly traded in the Nairobi Stock Exchange through the acquisition of its entire shareholding by I&M Group Plc (previously known as I&M Holdings PLC), a publicly listed company.');
    await page.getByText('Show More').click();
    await expect(page.locator('#page-wrap-in')).toContainText('About I&M BankI&M Bank was founded in 1974 as a financial services company and later converted to a commercial bank.I&M Bank is a wholly-owned subsidiary of I&M Group PLC (previously known as I&M Holdings PLC), a public company, listed at the Nairobi Securities Exchange (NSE). The bank possesses a rich heritage in banking. Having started in 1974, it evolved from a community financial institution to a publicly listed major regional commercial bank offering a full range of corporate and retail banking services.From June 2013, I&M Bank shares are publicly traded in the Nairobi Stock Exchange through the acquisition of its entire shareholding by I&M Group Plc (previously known as I&M Holdings PLC), a publicly listed company.I&M Bank is a dominant player in the Kenyan market that has been consistently growing, leveraging its enhanced digital and IT capabilities to position the Bank as a leader among its peers.British International Investment, a development finance institution wholly owned by the government of the United Kingdom owns approximately 10.68% of I&M Group Plc, the holding company of I&M Bank Ltd. In addition, I&M Bank has a technical support agreement with International Finance Corporation for staff training, product development and risk management. I&M Bank also enjoys medium-term foreign currency credit facilities from various Development Financial Institutions – Proparco, IFC, DEG and responsibility.I&M Bank’s international correspondent banks include major multinational banks such as Bank One Ltd, Citibank NA, Commerzbank AG, Deutsche Bank AG, ICICI Limited Mumbai, Mashreq Bank PLC, Standard Bank of South Africa and Standard Chartered Bank NY.I&M Bank’s international network includes Bank One Limited (Mauritius), I&M Bank (T) Limited, Tanzania and I&M Bank (Rwanda) Plc, Rwanda and I&M Bank Uganda Ltd.I&M GroupI&M Group Plc operates in five countries – Kenya, Tanzania, Rwanda, Uganda and Mauritius through its subsidiaries, affiliates and joint venture investments in each of these countries. Approximately 80% of I&M Holdings Plc’s asset value stems from our Kenyan operations with the largest entity by asset value being I&M Bank LIMITED.The Group has a major presence in Banking and Insurance, Manufacturing and Real Estate.In Tanzania and Rwanda the Group is represented by its Banking Subsidiaries, I&M Bank (T) Limited, Tanzania and I&M Bank (Rwanda) Plc respectively, while in Uganda its representation is through I&M Burbidge Capital (U) Limited a subsidiary of I&M Burbidge Capital Limited a corporate finance advisory arm of the Group.I&M Group also has 50% shareholding in Bank One Limited, Mauritius. An acquisition made jointly with the CIEL Finance of Mauritius, which is one of the largest and most reputable business groups in Mauritius. Bank One, with its customer base of over 50,000, a branch network of 9 branches in Mauritius, and a staff complement of over400 is a fast growing commercial bank in Mauritius.Other Group related companies include GA Insurance Company – popularly known as GA. GA is one of the oldest insurance companies operating in Kenya specializing in all classes of general insurance. Having its parentage from General Accident UK, it was incorporated as Kenyan Insurance Company in 1979. Enjoying its presence over 50 years, GA has earned its standing as one of the reputable insurance companies in Kenya. Show Less');
    await page.getByText('Show Less').click();
    await expect(page.getByRole('heading', { name: 'Our Objectives' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Our Objectives');
    await expect(page.locator('#page-wrap-in')).toContainText('To Become A Company Where The Best People Want To Work');
    await expect(page.locator('#page-wrap-in')).toContainText('The First Choice Where Customers Want To Do Business, And');
    await expect(page.locator('#page-wrap-in')).toContainText('Where Shareholder Are Happy With Their Investment');
    await expect(page.locator('div').filter({ hasText: /^To Become A Company Where The Best People Want To Work$/ }).nth(2)).toBeVisible();
    await expect(page.locator('div').filter({ hasText: /^The First Choice Where Customers Want To Do Business, And$/ }).nth(2)).toBeVisible();
    await expect(page.locator('div').filter({ hasText: /^Where Shareholder Are Happy With Their Investment$/ }).nth(2)).toBeVisible();
    await expect(page.getByRole('heading', { name: 'I&M Bank History' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('I&M Bank History');
    await expect(page.locator('#page-wrap-in')).toContainText('FormedInvestments & Mortgages Limited was formed and was based in Phoenix House. "I&M" as it was known, provided a much needed personalized financial service for Nairobi\'s business community.');
    await expect(page.locator('#page-wrap-in')).toContainText('RegisteredFormally registered as a Financial Institution under Banking Act and moved offices to Investment House, Kenyatta Avenue.');
    await expect(page.locator('#page-wrap-in')).toContainText('Conversion to commercial bankFollowing changes in the Central Bank of Kenya regulation, I&M formally converted into a commercial bank on 1st April 1996. This change coincided with a move to a more modern setting on Koinange Street.');
    await page.locator('div').filter({ hasText: 'I&M Bank History1 Park' }).getByLabel('Next slide').click();
    await expect(page.locator('#page-wrap-in')).toContainText('RestructureI&M was in the process of a major restructuring exercise in 1999 to coincide with the completion of 25 years of "I&M" name. The changes were initiated by the launch of a small, but important change - a new logo. This was intended to highlight I&M\'s evolution from a finance company into a commercial bank. I&M’s head offices were relocated to the prestigious I&M Bank House on 2nd Ngong Avenue, Nairobi-Kenya. This modern, spacious building was designed and built to fulfil the needs of our customers');
    await expect(page.locator('#page-wrap-in')).toContainText('I&M TowerThe new main branch of I&M opened at the glittering 16 storeys I&M Bank Tower located at the heart of the Central Business District of Nairobi-Kenya.');
    await expect(page.locator('#page-wrap-in')).toContainText('AcquisitionI&M acquired the assets of Biashara Bank of Kenya Limited. This merger resulted in increased market share, profitability and efficiency.');
    await expect(page.locator('#page-wrap-in')).toContainText('InvestmentDEG and PROPARCO, two leading international development financial institutions, invested K.Shs 377 million to acquire 11.96% shareholding in I&M.');
    await page.locator('div').filter({ hasText: 'I&M Bank History1 Park' }).getByLabel('Next slide').click();
    await expect(page.locator('#page-wrap-in')).toContainText('Regional Expansion - MauritiusIn February 2008, I&M acquired 50% shareholding in First City Bank (FCB) Limited, through a joint venture with the CIEL Group, Mauritius. FCB has subsequently rebranded itself as Bank One Limited.');
    await expect(page.locator('#page-wrap-in')).toContainText('Regional Expansion - TanzaniaIn January 2010, I&M Bank announced its entry into commercial banking in Tanzania with the acquisition of a majority stake in CF Union Bank Ltd (CFUB). Also participating in the equity buy-out was PROPARCO, a French Development Financial Institution, and an existing shareholder of I&M Bank together with The Kibo Fund and a well known and respected Tanzanian businessman Mr. Michael N Shirima who is a significant shareholder of Precision Air, the Tanzanian national airline.');
    await expect(page.getByText('Increased Investment by PROPARCOPROPARCO, the French Development Agency,')).toBeVisible();
    await expect(page.getByText('Regional Expansion - RwandaI&')).toBeVisible();
    await page.locator('div').filter({ hasText: 'I&M Bank History1 Park' }).getByLabel('Next slide').click();
    await expect(page.getByRole('heading', { name: 'Bank Awards' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('I&M Bank\'s quality and impressive growth, as well as progressive management practices, have been recognized with many awards over the years. We are a regular recipient of several awards in the annually held Banking Awards Ceremony in Nairobi, including several awards for Product Innovation and for the Most Efficient Bank. We have also been recognized in several Company of The Year Awards in every year that we have participated in them.');
    await expect(page.getByRole('img', { name: '2023: 7th Edition Connected' })).toBeVisible();
    await expect(page.getByRole('img', { name: ': Kenya Bankers Association.' })).toBeVisible();
    await expect(page.getByLabel('3 / 33', { exact: true }).getByRole('img', { name: ': Think Business' })).toBeVisible();
    await expect(page.getByLabel('3 / 33', { exact: true }).getByRole('img', { name: ': Think Business' })).toBeVisible();
    await expect(page.getByLabel('4 / 33', { exact: true }).getByRole('img', { name: ': Think Business' })).toBeVisible();
    await page.locator('#page-wrap-in section').filter({ hasText: 'Bank AwardsI&M Bank\'s quality' }).getByLabel('Next slide').click();
    await expect(page.getByLabel('5 / 33', { exact: true }).getByRole('img', { name: ': Think Business' })).toBeVisible();
    await page.locator('#page-wrap-in section').filter({ hasText: 'Bank AwardsI&M Bank\'s quality' }).getByLabel('Next slide').click();
    await expect(page.getByLabel('6 / 33', { exact: true }).getByRole('img', { name: ': Think Business' })).toBeVisible();
    await page.locator('#page-wrap-in section').filter({ hasText: 'Bank AwardsI&M Bank\'s quality' }).getByLabel('Next slide').click();
    await expect(page.getByLabel('7 / 33', { exact: true }).getByRole('img', { name: ': Think Business' })).toBeVisible();
    await page.locator('#page-wrap-in section').filter({ hasText: 'Bank AwardsI&M Bank\'s quality' }).getByLabel('Next slide').click();
    await expect(page.getByRole('img', { name: ': Legal Awards' })).toBeVisible();
    await page.locator('#page-wrap-in section').filter({ hasText: 'Bank AwardsI&M Bank\'s quality' }).getByLabel('Next slide').click();
    await expect(page.getByLabel('9 / 33', { exact: true }).getByRole('img', { name: ': Think Business' })).toBeVisible();
    await page.locator('#page-wrap-in section').filter({ hasText: 'Bank AwardsI&M Bank\'s quality' }).getByLabel('Next slide').click();
    await expect(page.getByLabel('10 / 33').getByRole('figure')).toBeVisible();
    await page.locator('#page-wrap-in section').filter({ hasText: 'Bank AwardsI&M Bank\'s quality' }).getByLabel('Next slide').click();
    await expect(page.getByLabel('11 / 33').getByRole('figure')).toBeVisible();
    await page.locator('#page-wrap-in section').filter({ hasText: 'Bank AwardsI&M Bank\'s quality' }).getByLabel('Next slide').click();
    await expect(page.getByLabel('12 / 33').locator('div').nth(2)).toBeVisible();
    await page.locator('#page-wrap-in section').filter({ hasText: 'Bank AwardsI&M Bank\'s quality' }).getByLabel('Next slide').click();
    await expect(page.getByLabel('13 / 33').getByRole('figure')).toBeVisible();
});


test('test I&M Bank Foundation', async ({ page }) => {
    await page.goto('https://www.imbankgroup.com/ke/about-us/im-foundation/');
    //await page.locator('#menu-item-16607').getByRole('link', { name: 'I&M Foundation' }).click();
    await expect(page.locator('.hero-section-4-container')).toBeVisible();
    await expect(page.locator('h1')).toContainText('I&M Bank Foundation');
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - I&M' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'I&M Foundation', exact: true })).toBeVisible();
    await page.getByText('I&M Foundation I&M Bank').click();
    await expect(page.locator('#page-wrap-in')).toContainText('I&M Foundation I&M Bank believes that the prosperity of business and society is inextricably linked and as such investing in society generates a positive multiplier effect that will benefit society, the environment and the economy. To actualize this belief, I&M Bank Kenya set up I&M Foundation to deliver a positive impact to society through social investment programs that create shared value for its stakeholders. The Foundation’s program approach is to work through implementing partners to deliver the objectives of the Foundation by seeking to leverage and complement resources, skills, experiences, knowledge and track records of partner organizations in a catalytic and value-adding manner. The Foundation is guided by the following:Our IdentityVisionOur vision is to see communities whose physical, social and economic environments are positively impacted as a result of our partnership.MissionOur mission is to deliver a positive impact to society through lasting solutions by engaging the planet, people and profit to create shared value for our stakeholders.Core ValuesTrustIntegrityRespect andInnovationOur PillarsThe Foundation supports initiatives in the following key strategic thematic areas, namely:');
    await expect(page.getByRole('heading', { name: 'Core Values' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Our Pillars' })).toBeVisible();
    await expect(page.getByText('The Foundation supports')).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Our Pillars' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('The Foundation supports initiatives in the following key strategic thematic areas, namely:');
    await expect(page.locator('#page-wrap-in section').filter({ hasText: 'I&M Foundation I&M Bank' }).locator('img')).toBeVisible();
    await expect(page.getByRole('heading', { name: 'All News and Announcements' })).toBeVisible();
    await expect(page.getByRole('link', { name: '04 Jan 2024 I&M Foundation' })).toBeVisible();
    await expect(page.getByRole('link', { name: '16 Dec 2023 I&M Foundation' })).toBeVisible();
    await expect(page.getByRole('link', { name: '13 Nov 2023 National Tree' })).toBeVisible();
    await expect(page.getByText('Jan 2024I&M Foundation hands over Ololo Dam to Kenya Wildlife Service following successful desilting and rehabilitation project 16 Dec 2023I&M Foundation sponsors Bank staff CSR day 13 Nov 2023National Tree Growing Day 28 Oct 2023I&M partners with MITI alliance to support schools greening programme 13 Apr 2023I&M Foundation, Moringa School in a grant partnership to create job opportunities in the digital space 28 Mar 2023I&M Foundation team reached the last mile manyatta in the relief food distribution in Samburu 23 Nov 2022I&M Foundation Supports Maa Trust Program 06 Sep 2022I&M Foundation Donates a School Bus to St. Ann Suresh Raja Girls High School 03 Sep 2022I&M Foundation Partnership with Strathmore University 13 Aug 2021I&M Foundation in partnership with Shamas Rugby Foundation supports the Take Control Program 02 Aug 2021I&M Foundation supports Secondary School Scholarships – Palmhouse Foundation 15 Jul 2021I&M Foundation’s partnership with the Maa Trust 13 Jul 2021Environmental Conservation Education – Nguzo Africa 30 Jun 2021I&M Foundation supports the Mentorship and Lifeskills Programme at St Ann’s Suresh Raja Girls High School 19 Feb 2021I&M Foundation Supports The Maa Beadwork 04 Feb 2021I&M Bank Foundation partners with Shamas Rugby Foundation on Life Skills Development for Youth 09 Sep 2020Partnership with St Ann Suresh Raja Girls High School 23 Jul 2020KCDF and I&M Bank Foundation Partnership 10 Jun 2020Response to COVID-19 – Support KNCCI, Mombasa Branch 27 Jan 2020Strathmore University and I&M Bank Ltd. Partnership 24 Sep 2019“Always give your best shot” – Meleah Oleche 02 Aug 2019Palmhouse Mentorship 05 Dec 2018Kibagare Feeding Programme – 2018 22 Aug 2018I&M Bank Donates Towards Kamili Mental Health Organization 15 Aug 2018I&M Bank Supports Students At Tangaza College 11 Jul 2018I&M Bank supports the friends of Ruiru Dam 16 Mar 2018Inauguration of St Ann Suresh Raja Girls High School, Kairi 07 Mar 2018I&M Bank Kenya Builds Dining Facility for St. Joseph Huruma 08 Feb 2018I&M Bank Supports Faraja Cancer Support Trust 03 Oct 2017Progress update on Scholarship Beneficiaries at Strathmore University 03 Oct 2017I&M Bank hosts St. Andrew’s Turi Education Day 01 Oct 2017Hope Campaign 01 May 2017Kibagare River Rehabilitation 01 Apr 2017Donation to Kamili Mental Health Organization 02 Feb 2017Central Bank’s Mountain Expedition 08 Sep 2016I&M Bank Annual Medical Camp 2016 18 Aug 2016Beyond Zero Campaign Mobile Clinic Handover 18 Aug 2016Palmhouse Foundation Mentorship 13 May 2016Jogoo Children’s Home 13 May 2016Seeds Orphanage Children’s Home 13 May 2016Muthurwa Primary School 13 May 2016Kamiti Youth Correctional Centre 13 May 2016I&M Bank Medical Camp 13 May 2016Annual Blood Donation Drive 13 May 2016I&M Blood Drive 2016 13 May 2015Environment- Tree Planting 2015 04 Mar 2014New Life Home Rescue Vehicle Donation 23 Oct 2013Gertrude’s Children’s Hospital Donation 14 Jun 2013Teule Kenya 14 Jun 2013Strathmore University Scholarship Programme 14 Jun 2013St Martin’s Kibagare – Annual Feeding Program 14 Jun 2013Nest Childrens Home 13 Jun 2013Kenya Red Cross Society – Greenhouse Program 18 Jul 2012Ground-Breaking Ceremony – St. Ann’s Suresh Raja Shah Girls Secondary School, Kairi 18 Jul 2012Nest Children’s Home 18 Jul 2012Roho Kwa Roho Foundation 18 Jul 2012Blood Donation 18 Jul 2012Kibagare Good News Centre Annual Feeding Programme 18 Jul 2012Port Rietz APDK Clinic In Mombasa 18 Jul 2012Cornel Ngaleku Childrens Centre (CNCC), Tanzania 18 Jul 2012Amara Charitable Trust 18 Jul 2012St. Anne Gichocho Official Opening Of Sponsored Dormitory 18 Jul 2012Palmhouse Foundation Mentorship Programme 18 Jul 2012Rhino Charge 25 May 2012Karura Forest')).toBeVisible();
});



test('test Annual Reports', async ({ page }) => {
    await page.goto('https://www.imbankgroup.com/ke/');
    await page.locator('#menu-item-16608').getByRole('link', { name: 'Annual Reports' }).click();
    await expect(page.getByText('About us', { exact: true })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('About us');
    await expect(page.locator('#menu-item-12178')).toBeVisible();
    await expect(page.locator('#menu-item-12178')).toContainText('Who We Are');
    await expect(page.locator('#menu-item-14104').getByRole('link', { name: 'I&M Foundation' })).toBeVisible();
    await expect(page.locator('#menu-item-14104')).toContainText('I&M Foundation');
    await expect(page.locator('#menu-item-11764').getByRole('link', { name: 'Annual Reports' })).toBeVisible();
    await expect(page.locator('#menu-item-11764')).toContainText('Annual Reports');
    await expect(page.locator('#menu-item-11766').getByRole('link', { name: 'Directors' })).toBeVisible();
    await expect(page.locator('#menu-item-11770').getByRole('link', { name: 'News' })).toBeVisible();
    await expect(page.locator('#menu-item-11769').getByRole('link', { name: 'I&M Voices' })).toBeVisible();
    await expect(page.locator('#menu-item-11771').getByRole('link', { name: 'Careers' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'GMT' })).toBeVisible();
    await expect(page.locator('#menu-item-11773').getByRole('link', { name: 'Partners' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Contact', exact: true })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Annual Reports & Financial' })).toBeVisible();
    await expect(page.locator('h1')).toContainText('Annual Reports & Financial Results');
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - Annual' })).toBeVisible();
    await expect(page.locator('div').filter({ hasText: 'Annual Reports & Financial' }).nth(3)).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Financial Results', exact: true })).toBeVisible();
    await expect(page.locator('#financial-results')).toContainText('Financial Results');
    await expect(page.getByRole('link', { name: 'I&M Bank Financial Results Full Year' })).toBeVisible();
    await expect(page.locator('.feature-42-header-rs > .drop-down-cont > .dropdown > .dropdown-select-cont').first()).toBeVisible();
    await expect(page.locator('#financial-results')).toContainText('2023');
    await page.locator('.feature-42-header-rs > .drop-down-cont > .dropdown > .dropdown-select-cont').first().click();
    await expect(page.locator('#page-wrap-in')).toContainText('Financial Results 2023 2023 2022 2021 2020 2019 2018 2017 2016 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Full Year 2023 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q3 2023 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Half Year 2023 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q1 2023 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results 2022 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q3 2022 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Half Year 2022 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q1 2022 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results 2021 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q3 2021 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Half Year 2021 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q1 2021 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results 2020 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q3 2020 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results HY 2020 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q1 2020 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results 2019 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q3 2019 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results HY 2019 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q1 2019 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4} I&M Bank Financial Results 2018 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q3 2018 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results HY 2018 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q1 2018 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results 2017 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q3 2017 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results HY 2017 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q1 2017 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}Giro Commercial Bank Financial Results 2016 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results 2016 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q3 2016 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results HY 2016 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Financial Results Q1 2016');
    await page.locator('#page-wrap-in section').filter({ hasText: 'Financial Results 2023 2023' }).click();
    await expect(page.getByRole('link', { name: 'I&M Bank Financial Results Q3' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'I&M Bank Financial Results Half Year' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'I&M Bank Financial Results Q1' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Annual Reports', exact: true })).toBeVisible();
    await expect(page.getByText('.cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Limited Annual Report and Consolidated Financial Statements – 2022 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Limited Annual Report and Consolidated Financial Statements – 2021 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Limited Annual Report and Financial Statements 2020 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Limited Annual Report and Financial Statements 2019 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Limited Annual Report and Financial Statements 2018 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Limited Annual Report and Financial Statements 2017 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2016 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2015 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2014 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2013 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2012 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2011 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2010 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2009 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2008 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2007 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2006 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2005 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report 2004 .cls-3{fill:#adacac}.cls-4{fill:#f4f4f4}I&M Bank Annual Report')).toBeVisible();
    await expect(page.locator('#annual-reports > .feature-42-header > .feature-42-header-rs > .drop-down-cont > .dropdown > .dropdown-select-cont')).toBeVisible();
    await expect(page.locator('#annual-reports')).toContainText('2022');
});
//directors 
test('test directors', async ({ page }) => {
    await page.locator('#menu-item-16609').getByRole('link', { name: 'Directors' }).click();
    await expect(page.getByText('Our Vision, Mission and')).toBeVisible();
    await expect(page.getByRole('blockquote')).toContainText('Our Vision, Mission and Culture statements hold the keys to the philosophy on which we base ourselves on what we do.');
    await expect(page.getByText('Message from the Board')).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Our Board' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Our Board Of Directors includes members with diverse experience in various fields including law, banking and management.');
    await expect(page.locator('.feature-43-body')).toBeVisible();
    await expect(page.getByRole('link', { name: 'Mr. Daniel Ndonye Chairman of' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Mr. S. B. R. Shah Non-' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Mr. Sarit S. Raja Shah Group' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Mr. Sachit Shah Non-Executive' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Mr. Gul Khan Chief Executive' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Mr. Soundararajan Independent' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Dr. Nyambura Koigi' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Mr. Alan James Dodd' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Mr. Muchemi Wambugu' })).toBeVisible();
    await expect(page.getByText('The Directors collectively')).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('The Directors collectively have vast experience arising from their varied backgrounds in different fields including Banking, General Management, Law, Accounting and Investment Analysis, apart from hands-on experience in various industries.');
});
//news
test('test news', async ({ page }) => {
    await page.locator('#menu-item-16610').getByRole('link', { name: 'News' }).click();
    await expect(page.getByText('About us', { exact: true })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('About us');
    await expect(page.locator('div').filter({ hasText: 'Corporate news and' }).nth(3)).toBeVisible();
    await expect(page.locator('h1')).toContainText('Corporate news and announcements');
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - News' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'All News & Announcements' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('All News & Announcements');
    await expect(page.getByRole('link', { name: '25 Mar 2024 I&M Group PLC' })).toBeVisible();
    await expect(page.getByRole('link', { name: '28 Aug 2023 I&M Group PLC' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('I&M Group PLC delivers 20% Revenue and 15% Profit After Tax Growth');
    await expect(page.locator('#page-wrap-in')).toContainText('I&M Group PLC delivers 23% growth in Operating Income with a significant growth of 28% in the Retail Segment');
    await expect(page.getByRole('link', { name: '07 Aug 2023 Resignation of Mr' })).toBeVisible();
    await expect(page.getByRole('link', { name: '18 Jul 2023 Odyssey Energy' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Odyssey Energy Solutions and I&M Bank join forces to drive renewable energy investments');
    await expect(page.getByRole('link', { name: '26 May 2023 I&M Group PLC' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('I&M Group PLC delivers 29% growth in Operating Profit for the first Quarter of 2023');
    await expect(page.getByRole('link', { name: '03 May 2023 I&M Bank responds' })).toBeVisible();
    await expect(page.getByRole('link', { name: '23 Apr 2023 I&M Bank Limited' })).toBeVisible();
    await expect(page.getByRole('link', { name: '13 Apr 2023 I&M Foundation,' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Mar 2023 2022 Financial Results' })).toBeVisible();
    await expect(page.getByRole('link', { name: '07 Mar 2023 Redington Limited' })).toBeVisible();
    await expect(page.getByRole('link', { name: '15 Feb 2023 I&M Bank Waives' })).toBeVisible();
    await expect(page.getByRole('link', { name: '05 Dec 2022 Home player bags' })).toBeVisible();
    await expect(page.locator('#page-wrap-in section').filter({ hasText: 'All News & Announcements All' })).toBeVisible();
    await expect(page.getByRole('link', { name: '10 Feb 2012 I&M Bank receives' })).toBeVisible();
});
//I&M voices
test('test aboutus news', async ({ page }) => {
    await page.locator('#menu-item-16611').getByRole('link', { name: 'I&M Voices' }).click();
    await expect(page.locator('#page-wrap-in')).toContainText('About us');
    await expect(page.getByRole('link', { name: 'Who We Are' })).toBeVisible();
    await expect(page.locator('.hero-section-4-container')).toBeVisible();
    await expect(page.getByRole('heading', { name: 'I&M Voices' })).toBeVisible();
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - I&M Voices' })).toBeVisible();
    await expect(page.getByText('Recently Added 24 Jan 2023How')).toBeVisible();
    await expect(page.getByRole('link', { name: '24 Jan 2023 How to create a' }).first()).toBeVisible();
    await expect(page.getByRole('link', { name: '12 Jan 2023 How does I&M OTG' }).first()).toBeVisible();
    await expect(page.getByRole('link', { name: 'Dec 2022 Holiday budgeting tips' }).first()).toBeVisible();
    await expect(page.getByRole('heading', { name: 'All Blog Entries' })).toBeVisible();
    await expect(page.getByText('All Blog Entries All All budgeting Business Businesss during Covid Candid Corporate Culture Corporate Culture Covid-19 Cultural Transformation festivities Finance Financial Plan Financial Planning I&M Unsecured Personal Loan Loan Managing Credit Money Organisational Culture perfect balance in the workplace Personal Finance Repetitional Risk Risk Risk Management Stress & Resilience Wealth Management 24 Jan 2023How to create a personal financial plan 12 Jan 2023How does I&M OTG Web and App protect your finances? 15 Dec 2022Holiday budgeting tips 06 Dec 2022Do you Really Understand Credit Cards? 29 Nov 2022The 6-step financial planning process for small businesses 01 Nov 20224 Signs that you’re excessively invested in your work. 18 Oct 2022Financial planning for small businesses 06 Oct 20225 things to look at when choosing your potential Business banking partner. 14 Sep 2022Stress & Resilience; The Perfect Balance in the Workplace 14 Aug 2022Candid Corporate Culture 05 Aug 2022Ways to achieve financial freedom 06 Jul 2022Here are 7 tips to help you start investing 30 Jun 2022Managing Credit 29 Jun 2022SURVIVE INFLATION WITH THESE 5 TIPS 14 May 2022Digitizing the Banking Industry in a Fast-Moving World 27 Apr 20225 Simple Ways to Save Money 11 Mar 2022Breaking The Bias – International Women’s Month 24 Feb 2022Reputational Risk 18 Jan 2022Ways you can turn your goals and resolutions into success 25 Dec 2021Ways to save money during seasonal holidays 24 Dec 2021Steps to Building a High-Performing Organisational Culture 10 Dec 2021Importance of Organisational Culture and How to Build One 06 Dec 2021How To Win Clients with Great Customer Experience 02 Nov 2021Don’t be scared, be prepared - Managing Social Media Crisis 15 Oct 2021What’s the future form of money? 29 Sep 2021Lessons we have learnt during the Covid-19 turbulent times 05 Aug 2021No Big Talk. No Small Talk. Just A Straight Talk About Wealth Management 26 Jul 2021How do you know its time to rebrand your business? 09 Jun 2021Building an Effective Business Strategy 18 May 2021Cyber Security Is Bound To Make An Impact In Your Business 16 May 2021What to consider when setting out an investment 15 May 2021E-commerce measures merchants should take to protect their customers from frauds 30 Apr 2021MSMEs Resilience in turbulent Times. 23 Nov 2020Cyber-security in an era where digital banking is the order of the day 10 Nov 2020Why did we rebrand? 31 Oct 2020Importance of monitoring your business’s financial health. 04 Oct 2020Cushioning your business during a pandemic or crisis 04 Sep 2020Impacts of COVID-19 on the Global Financial System 11 Aug 2020The positive side of the Coronavirus pandemic 07 Aug 2020Holistic health for the mind and body 07 Aug 2020Ambition in business: An important intangible asset you need for your business 25 Jun 2020All you need to know about Trade Finance 18 Jun 2020Sustenance for small, medium and large businesses enterprises during COVID-')).toBeVisible();
    const pagePromise = page.waitForEvent('popup');
});

//Career
test('test Career', async ({ page }) => {
    await page.getByRole('link', { name: 'Career', exact: true }).click();
    //const page = await pagePromise;
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - Career at I&' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Build your Career at I&M Bank' })).toBeVisible();
    await expect(page.locator('h1')).toContainText('Build your Career at I&M Bank');
    await expect(page.locator('#page-wrap-in')).toContainText('Grow and Prosper');
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - Career at I&' })).toBeVisible();
    await expect(page.getByText('Want to join us?Banking is a')).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Want to join us?');
    await expect(page.locator('#page-wrap-in')).toContainText('Banking is a profession that offers a huge variety of opportunities, as well as the possibility of rapid career progression, all with good pay and benefits. For those willing to accept the challenge, the rewards can be great! Want to join our team? click on open positions to see if any opportunity interests you!');
    await expect(page.getByRole('link', { name: 'Open Positions' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'What\'s in it for you?' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Here is what you can expect');
    await expect(page.getByText('1A fast-paced tech environment')).toBeVisible();
    await expect(page.getByText('2Room for own initiatives and')).toBeVisible();
    await expect(page.getByText('3Team spirit and commitment')).toBeVisible();
    await expect(page.getByText('4A team of young and seasoned')).toBeVisible();
    await expect(page.getByText('5Career advancement and')).toBeVisible();
    await expect(page.getByText('6Continuous growth and')).toBeVisible();
    await expect(page.getByText('7Supportive and approachable')).toBeVisible();
    await expect(page.getByText('8Good work-life balance and')).toBeVisible();
    await expect(page.getByText('9Competitive salaries and')).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('A career in I&M Bank is open to everyone, regardless of race, gender, national origin or age');
    await expect(page.getByRole('heading', { name: 'The I&M Way' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('How we work at I&M Bank');
    await expect(page.locator('.feature-17-body-col > .card > .card-body').first()).toBeVisible();
    await expect(page.locator('.feature-17-body > div:nth-child(2) > .card > .card-body').first()).toBeVisible();
    await expect(page.locator('.feature-17-body > div:nth-child(3) > .card > .card-body').first()).toBeVisible();
    await expect(page.locator('.feature-17-body > div:nth-child(4) > .card > .card-body').first()).toBeVisible();
    await expect(page.locator('.feature-17-body > div:nth-child(5) > .card > .card-body').first()).toBeVisible();
    await expect(page.locator('.feature-17-body > div:nth-child(6) > .card > .card-body')).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Our Values' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Values we live by');
    await expect(page.locator('section:nth-child(10) > .container > .row > .col > .feature-17-container > .feature-17-body > div > .card > .card-body').first()).toBeVisible();
    await expect(page.locator('section:nth-child(10) > .container > .row > .col > .feature-17-container > .feature-17-body > div:nth-child(2) > .card > .card-body')).toBeVisible();
    await expect(page.locator('section:nth-child(10) > .container > .row > .col > .feature-17-container > .feature-17-body > div:nth-child(3) > .card > .card-body')).toBeVisible();
    await expect(page.locator('section:nth-child(10) > .container > .row > .col > .feature-17-container > .feature-17-body > div:nth-child(4) > .card > .card-body')).toBeVisible();
    await expect(page.locator('section:nth-child(10) > .container > .row > .col > .feature-17-container > .feature-17-body > div:nth-child(5) > .card > .card-body')).toBeVisible();
    await expect(page.locator('#page-wrap-in section').filter({ hasText: 'Apply NowI&M Bank is a great' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Apply Now' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('I&M Bank is a great place to work. You can achieve financial growth, career growth and personal growth with effort, dedication and hard work.');
    await expect(page.getByRole('link', { name: 'Apply Now' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Are you interested?' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Are you interested?');
    await fillAndSubmitForm(page)
});
//partners
test('test partners', async ({ page }) => {
    await page.locator('#menu-item-16613').getByRole('link', { name: 'Partners' }).click();
    await expect(page.getByText('About usWho We Are I&M')).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('About us');
    await expect(page.locator('div').filter({ hasText: 'I&M Bank Partners' }).nth(3)).toBeVisible();
    await expect(page.locator('h1')).toContainText('I&M Bank Partners');
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - Partners' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'We value our partners' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('We value and respect our various national and international partners as they help us manage and grow our business, and yours.');
    await expect(page.locator('.card > a').first()).toBeVisible();
    await expect(page.locator('div:nth-child(2) > .card > a')).toBeVisible();
    await expect(page.locator('div:nth-child(3) > .card > a')).toBeVisible();
    await expect(page.locator('div:nth-child(4) > .card > a')).toBeVisible();
    await expect(page.locator('div:nth-child(5) > .card > a')).toBeVisible();
    await expect(page.locator('div:nth-child(6) > .card > a')).toBeVisible();
    await expect(page.locator('div:nth-child(7) > .card > a')).toBeVisible();
    await expect(page.locator('div:nth-child(8) > .card > a')).toBeVisible();
    await expect(page.locator('div:nth-child(9) > .card > a')).toBeVisible();
});
//contact
test('test contact', async ({ page }) => {
    await page.locator('#menu-item-16614').getByRole('link', { name: 'Contact' }).click();
    await expect(page.getByRole('heading', { name: 'Get in touch today!' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('We are on your side!');
    await expect(page.getByText('+254 719 088 000 +254 20 322')).toBeVisible();
    await expect(page.getByText('Customer Carecustomercare@')).toBeVisible();
    await expect(page.locator('div:nth-child(3) > .card > .card-body')).toBeVisible();
    await expect(page.getByRole('link', { name: 'Facebook' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Twitter' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Instagram' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Linkedin' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Youtube' })).toBeVisible();
    await expect(page.locator('.footer-notes')).toBeVisible();
});
//corporate
test('test corporate', async ({ page }) => {
    await page.locator('#menu-item-23229').getByRole('link', { name: 'Corporate Profile' }).click();
    await expect(page.getByRole('heading', { name: 'I&M Bank Kenya Corporate' })).toBeVisible();
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - I&M Bank' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'I&M Bank Kenya Profile' })).toBeVisible();
});