import { test, expect } from '@playwright/test';
import { navigateTo, scrollToBottom } from '../helpers/utilities';



test('test', async ({ page }) => {
    await page.goto('https://www.imbankgroup.com/ke/');
    await page.hover('#menu-item-12094');

    await page.$('text=Cards +');
    await page.hover('text=Cards');
    await page.getByRole('link', { name: 'Credit Cards' }).click();
    await expect(page.getByText('Personal BankingAccounts')).toBeVisible();
    await expect(page.locator('h1')).toBeVisible();
    await expect(page.locator('h1')).toContainText('I&M Bank Credit Cards');
    await expect(page.locator('#page-wrap-in')).toContainText('Treat yourself with best credit cards in Kenya');
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - Credit Cards' })).toBeVisible();
    await expect(page.locator('li').filter({ hasText: 'Unlimited FREE Access to over' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Unlimited FREE Access to over 800 Airport Lounges');
    await expect(page.locator('li').filter({ hasText: 'Up to 50 days Credit period' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Up to 50 days Credit period');
    await expect(page.locator('li').filter({ hasText: 'Minimum payment up to 15%' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Minimum payment up to 15%');
    await expect(page.locator('h2').filter({ hasText: 'I&M Bank Credit Cards' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Experience freedom by choosing among a range of best Visa credit cards in Kenya with many advantages like free credit period, loyalty points for usage and so much more');
    await expect(page.getByRole('link', { name: 'I&M Visa International Gold' }).nth(1)).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('I&M Visa International Gold Credit Card');
    await expect(page.locator('#page-wrap-in')).toContainText('Kes 3500 Joining Fee');
    await expect(page.locator('#page-wrap-in')).toContainText('Free Credit facility up-to 50 daysCash Advance limit up to 30% of the credit limit.Attractive reward pointsWorldwide acceptance');
    await page.getByRole('link', { name: 'I&M Visa International Gold' }).nth(1).click();
    await expect(page.locator('p').filter({ hasText: 'Personal Banking' }).locator('a')).toBeVisible();
    await expect(page.locator('#menu-item-10550').getByRole('link', { name: 'Accounts' })).toBeVisible();
    await expect(page.locator('h1')).toContainText('Visa International Gold Credit Card');
    await expect(page.locator('#page-wrap-in')).toContainText('Visa Gold Credit Card A premium Visa Gold Credit Card, Well Worth Your Signature.');
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - I&M Visa' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Visa Gold Credit Card A premium Visa Gold Credit Card, Well Worth Your Signature.');
    await expect(page.locator('ul').filter({ hasText: 'Worldwide Acceptance Free' }).locator('#Capa_1')).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Worldwide Acceptance');
    await expect(page.locator('li').filter({ hasText: 'Free credit period up to 50' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Free credit period up to 50 days');
    await expect(page.locator('li').filter({ hasText: 'Pay upto as low as 15% of' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Pay upto as low as 15% of total outstanding balance');
    await expect(page.getByRole('img', { name: 'I&M Bank Kenya - I&M Visa' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Overview' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Features' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Requirements' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'I&M Visa International Gold Credit Card', exact: true })).toBeVisible();
    await expect(page.locator('#overview')).toContainText('The I&M Visa International Gold Credit Card is truly a product well worth your Signature. The card is accepted worldwide in all Visa accepting ATMs, shops, restaurants and other Visa merchants as well as for making online purchases. It has attractive features such as encashable loyalty points for usage, SMS alerts for usage to enhance security from fraud, revolving credit and is also available for nominated family members of the main cardholder. Get an I&M Bank International Gold Card and have a whole world of privileges in your purse.');
    await expect(page.getByRole('heading', { name: 'I&M Bank Benefits' })).toBeVisible();
    await expect(page.locator('#features')).toContainText('I&M Bank Benefits');
    await expect(page.getByText('AcceptanceThe card is')).toBeVisible();
    await expect(page.locator('#features')).toContainText('Acceptance');
    await expect(page.locator('#features')).toContainText('The card is accepted worldwide in all Visa accepting ATMs, shops, restaurants, and other Visa merchants as well as for making online purchases.');
    await expect(page.getByRole('heading', { name: 'Prestige' })).toBeVisible();
    await expect(page.locator('#features')).toContainText('Prestige as a VISA cardholder and buildup of a recognized credit history');
    await expect(page.getByRole('heading', { name: 'Attractive Reward Points' })).toBeVisible();
    await expect(page.locator('#features')).toContainText('Earn 0.3% of your spend amount when you transact on POS (Point of Sale) or online shopping. 1 Point = 1 Kes');
    await expect(page.getByRole('heading', { name: 'Free credit period' })).toBeVisible();
    await expect(page.locator('#features')).toContainText('Up to 50 days');
    await expect(page.getByRole('heading', { name: 'Payment', exact: true })).toBeVisible();
    await expect(page.locator('#features')).toContainText('Convenient option to pay up to as low as 15% of total outstanding balance.');
    await expect(page.getByRole('heading', { name: 'Credit Enhancement' })).toBeVisible();
    await expect(page.locator('#features')).toContainText('Automatic credit enhancement on renewal, subject to satisfactory usage.');
    await expect(page.getByRole('heading', { name: 'Supplementary cards for' })).toBeVisible();
    await expect(page.locator('#features')).toContainText('Supplementary cards for family members on request');
    await expect(page.getByRole('heading', { name: 'Visa Infinite Benefits' })).toBeVisible();
    await expect(page.locator('.card-body > .media').first()).toBeVisible();
    await expect(page.locator('#features')).toContainText('Smart Change - If you already hold a credit card and wish TO SWITCH to the I&M Bank International Visa Classic Card, we will take over the outstanding balance of your old credit card and give you the option for paying this outstanding balance in 3 easy monthly instalments AT ZERO INTEREST RATE');
    await expect(page.locator('div:nth-child(2) > .card > .card-body > .media')).toBeVisible();
    await expect(page.locator('#features')).toContainText('Signature Points - A loyalty points programme that rewards you every time you spend on your classic card. Earn 1 loyalty point for every Kes 500');
    await expect(page.locator('div:nth-child(3) > .card > .card-body')).toBeVisible();
    await expect(page.locator('#features')).toContainText('Smart Pay - Specially in-built financing feature to enable you to make large purchases through your classic card.');
    await expect(page.locator('div:nth-child(4) > .card > .card-body')).toBeVisible();
    await expect(page.locator('#features')).toContainText('SignatureAlert: a. Get notified by SMS every time a transaction of over Kshs 3,000 is carried out b. A secure online transaction using Verified by Visa Authorization Code c. SafeCard App that allows you to block and unblock your card anytime anywhere.');
    await expect(page.getByRole('heading', { name: 'Credit Card Payment' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Want to make Payments for' })).toBeVisible();
    await page.getByRole('button', { name: 'Want to make Payments for' }).click();
    await expect(page.getByLabel('Want to make Payments for').getByRole('list')).toContainText('To pay using Mpesa Pay Bill, follow the below instructions: - Go to Mpesa Menu, Lipa na M-PESA - Select Pay Bill - Enter the Business no “872649” - Enter Account Number “Your 16 digit Card Number” - Enter Amount - And finally enter your Mpesa PIN to complete the transaction To pay using Mpesa Xpress - Go to "Online Services" on the Home Page, Select M-PESA Xpress and follow the following instructions - Enter the full 16 digit Credit Card Number and amount to pay - Enter your Phone number - You will then receive a pop up on your phone requesting you to enter your Mpesa PIN to complete the transaction (Make sure your mobile device screen is unlocked)');
    await page.getByRole('button', { name: 'Want to make Payments for' }).click();
    await expect(page.getByRole('heading', { name: 'Card Tariff and Charges' })).toBeVisible();
    await expect(page.locator('#features')).toContainText('Joining FeeKes 3,500');
    await expect(page.locator('#features')).toContainText('Supplementary Joining Fee');
    await expect(page.locator('#features')).toContainText('Annual FeesKes 4,000');
    await expect(page.locator('#features')).toContainText('Supplementary Annual FeesKes 2,000');
    await expect(page.locator('#features')).toContainText('Credit PeriodUp to 50 days');
    await expect(page.locator('#features')).toContainText('Roll-over Amount90%');
    await expect(page.locator('#features')).toContainText('Minimum Payment10%');
    await page.getByText('Cash Advance30% of credit').click();
    await expect(page.getByRole('heading', { name: 'Cash Advance', exact: true })).toBeVisible();
    await expect(page.locator('#features')).toContainText('30% of credit limit');
    await expect(page.getByRole('heading', { name: 'Revolving Credit Interest' })).toBeVisible();
    await expect(page.locator('#features')).toContainText('3.5% per month on the actual daily outstanding balance');
    await expect(page.getByRole('heading', { name: 'Late Payment Penalty Rate' })).toBeVisible();
    await expect(page.locator('#features')).toContainText('6% flat on outstanding minimum payment amount on due date, Kshs 1,000/- maximum');
    await expect(page.getByRole('heading', { name: 'Over Limit Charge' })).toBeVisible();
    await expect(page.locator('#features')).toContainText('Over Limit ChargeKes 1,500');
    await expect(page.locator('#features')).toContainText('Cash Advance Charge7.50% of cash advanced');
    await expect(page.locator('#features')).toContainText('Unpaid Instruments Handling FeesKShs. 2,000');
    await expect(page.locator('#features')).toContainText('Card Replacement FeesKShs. 1,000');
    await expect(page.locator('#features')).toContainText('Credit Life Insurance % of approved limit0.36% p.a');
    await expect(page.getByRole('heading', { name: 'Terms and Conditions', exact: true })).toBeVisible();
    await expect(page.locator('#features')).toContainText('Terms and Conditions');
    await expect(page.locator('#terms-and-conditions')).toBeVisible();
    await expect(page.locator('#terms-and-conditions-heading')).toContainText('Terms and Conditions');
    await page.getByRole('button', { name: 'Terms and Conditions +' }).click();
    await expect(page.getByLabel('Terms and Conditions').getByRole('list')).toContainText('Some of the features described above may be amended, varied or unavailable at some point in time Signature Change and Signature Pay facilities are at the discretion of I&M Bank. Card issuance is subject to Terms and Conditions of I&M Bank International Visa Infinite Credit Card Ease carefully read the Terms & Conditions and applicable charges prior to applying.');
    await page.locator('#terms-and-conditions-heading').click();
    await expect(page.getByRole('heading', { name: 'Want to apply for Credit Card?' })).toBeVisible();
    await expect(page.locator('#requirements')).toContainText('Download the form from the download section and submit it to the nearest branch with the required documentation.');
    await expect(page.getByRole('link', { name: 'Application Form' })).toBeVisible();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('link', { name: 'Application Form' }).click();
    const page1 = await page1Promise;
    await page.locator('#page-wrap-in section').filter({ hasText: 'Are you interested in I&M' }).click();
    await expect(page.getByRole('heading', { name: 'Are you interested in I&M' })).toBeVisible();
    await expect(page.locator('#page-wrap-in')).toContainText('Are you interested in I&M Visa International Gold Credit Card?');
    await expect(page.locator('#gform_26 div').filter({ hasText: 'Full Name*Email Address*' })).toBeVisible();
    await expect(page.locator('#field_26_1')).toContainText('Full Name*');
    await expect(page.locator('#field_26_2')).toContainText('Email Address*');
    await expect(page.locator('#field_26_3')).toBeVisible();
    await expect(page.locator('#field_26_3')).toContainText('Phone Number*');
    await expect(page.getByText('Nearest Branch*Kenyatta')).toBeVisible();
    await expect(page.locator('#field_26_4')).toContainText('Nearest Branch*Kenyatta Avenue2nd Ngong AvenueSarit CentreBiashara StreetIndustrial AreaKisumuKaren ConnectionPanari Centre1 ParkParklandsWilson AirportOngata RongaiSouth CNyali Cinemax MsaLangata LinkValley Arcade BranchEldoretNakuru BranchRiverside BranchKisiiChangamwe MsaMalindiNyeriThika BranchVillage MarketLavington MallKitaleLunga LungaYaya CentreGateway MallRuarakaCross RoadNanyukiSpring ValleyMeruEldama ParkDunga RoadRidge CourtHaile Selassie Ave Msa');
    await expect(page.getByText('Select one of the options')).toBeVisible();
    await expect(page.getByText('Select one of the options below:* I am interested, please contact me I want')).toBeVisible();
    await expect(page.locator('#label_26_5_0')).toContainText('I am interested, please contact me');
    await expect(page.locator('#label_26_5_1')).toContainText('I want some clarification as below');
    await expect(page.locator('#field_26_6')).toBeVisible();
    await expect(page.locator('#field_26_6')).toContainText('Comment*');
    await expect(page.getByText('Consent*')).toBeVisible();
    await expect(page.locator('#field_26_7')).toContainText('Consent*');
    await expect(page.getByLabel('I have read and understood')).toBeVisible();
    await page.getByLabel('I have read and understood').check();
    await expect(page.getByText('Validate you\'re human')).toBeVisible();
    await expect(page.locator('#field_26_9')).toContainText('Validate you\'re human');
    await expect(page.getByRole('button', { name: 'Submit' })).toBeVisible();
    await page.getByPlaceholder('Enter Your Name').click();
    await page.getByPlaceholder('Enter Your Name').fill('my first');
    await page.locator('#field_26_2').click();
    await page.getByPlaceholder('Enter Your Email Address').fill('example@gmail.com');
    await page.locator('#field_26_3').click();
    await page.getByPlaceholder('Enter Phone Number').fill('0720454576');
    await page.getByLabel('Nearest Branch*').selectOption('Eldoret');
    await page.getByLabel('I am interested, please').check();
    await page.getByPlaceholder('Enter your Comments').click();
    await page.getByPlaceholder('Enter your Comments').fill('hgb nncws');
    // await page.frameLocator('iframe[name="a-rha0338iqgo2"]').getByLabel('I\'m not a robot').click();
});